spring:
    application:
      name: SkyFlow
    datasource:
      username: ${PG_USERNAME}
      password: ${PG_PASSWORD}
      url: jdbc:postgresql://skyflow-db.postgres.database.azure.com:5432/postgres?user=${spring.datasource.username}&password=${spring.datasource.password}&sslmode=require
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        platform: postgresql
        mode: always  # Change it to 'always' if you want to initialize data on app start.
        continue-on-error: true
jwt:
  variables:
    jwtSecret:
    jwtExpirationMs:
opensky:
  username:
  password:
springdoc:
  swagger-ui:
    use-root-path: true