name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install OpenSky
        run: git clone https://github.com/openskynetwork/opensky-api.git && cd opensky-api/java && mvn clean install
      - name: Build with Maven
        run: mvn install -DskipTests --file pom.xml
#        run: mvn --batch-mode --update-snapshots install